const Actions = {
  LOADINGMODAL : 'LOADINGMODAL' ,
  GETSANDBOX : 'GETSANDBOX' ,
  PUTSANDBOX : 'PUTSANDBOX' ,
  LOGIN : 'LOGIN',
  GETHISTORYSANDBOX:'GETHISTORYSANDBOX',
  PUTHISTORYSANDBOX:'PUTHISTORYSANDBOX',
  GETRESTARTSANDBOX:'GETRESTARTSANDBOX',
  GETHOMEINFO : 'GETHOMEINFO' ,
  GETUSERINFO : 'GETUSERINFO'
}

export default Actions;
